---

- name: create | Create ssl key
  community.crypto.openssl_privatekey:
    path: "{{ openssl_key_directory }}/{{ item.name }}.pem"
    mode: "600"
  loop: "{{ openssl_items }}"
  loop_control:
    label: "{{ item.name }}"

- name: create | Create ssl csr
  community.crypto.openssl_csr:
    path: "{{ openssl_csr_directory }}/{{ item.name }}.csr"
    privatekey_path: "{{ openssl_key_directory }}/{{ item.name }}.key"
    common_name: "{{ item.common_name }}"
    mode: "640"
    owner: "{{ openssl_file_owner }}"
    group: "{{ openssl_file_group }}"
  loop: "{{ openssl_items }}"
  loop_control:
    label: "{{ item.name }}"

# Остальные задачи также нужно обернуть в цикл и передать переменную item
