---
# tasks file for openssl
- name: install packages
  package:
    name: "{{ openssl_packages }}"
  register: openssl_install_packages
  until: openssl_install_packages is succeeded
  retries: 3

- name: create ssl key
  openssl_privatekey:
    path: "{{ openssl_key_directory }}/{{ item.name }}.key"
  loop: "{{ openssl_items }}"

- name: create ssl csr
  openssl_csr:
    path: "{{ openssl_csr_directory }}/{{ item.name }}.csr"
    privatekey_path: "{{ openssl_key_directory }}/{{ item.name }}.key"
    common_name: "{{ item.common_name }}"
  loop: "{{ openssl_items }}"

- name: create ssl certificates
  openssl_certificate:
    path: "{{ openssl_crt_directory}}/{{ item.name }}.crt"
    privatekey_path: "{{ openssl_key_directory }}/{{ item.name }}.key"
    csr_path: "{{ openssl_csr_directory }}/{{ item.name }}.csr"
    provider: selfsigned
  loop: "{{ openssl_items }}"

- name: cretae PKCS#12 file
  openssl_pkcs12:
    action: export
    path: "{{ openssl_key_directory }}/{{ item.name }}.p12"
    friendly_name: "{{ item.name }}"
    privatekey_path: "{{ openssl_key_directory }}/{{ item.name }}.key"
    certificate_path: "{{ openssl_crt_directory}}/{{ item.name }}.crt"
    state: present
  loop: "{{ openssl_items }}"
